name: stl_to_gltf_converter
description: A Flutter app that converts STL files to glTF/glb.
publish_to: "none"

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  file_picker: ^10.1.2
  flutter:
    sdk: flutter
  flutter_inappwebview: ^6.1.5
  path_provider: ^2.1.5
  shelf: ^1.4.2
  shelf_static: ^1.1.3
  vector_math: ^2.1.4
  webview_flutter: ^4.11.0

flutter:
  uses-material-design: true
