name: stl_to_gltf_converter
description: A Flutter app that converts STL files to glTF/glb.
publish_to: "none"

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  file_picker: ^10.1.2
  flutter:
    sdk: flutter
  flutter_scene: ^0.9.2-0
  path_provider: ^2.1.5
  vector_math: ^2.1.4

flutter:
  uses-material-design: true
